version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nextjs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nextjs_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextjs_network

volumes:
  postgres_data:

networks:
  nextjs_network:
