services:
  app:
    build:
      context: .
    image: nextjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  db:
    image: postgres:13
    container_name: agile-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emDvuwU6
      POSTGRES_DB: agile_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextjs_network

volumes:
  postgres_data:

networks:
  nextjs_network: